#

# Data Loading

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

splits = {'train': 'train.csv', 'validation': 'validation.csv', 'test': 'test.csv'}
telco_churn_df = pd.read_csv("hf://datasets/aai510-group1/telco-customer-churn/" + splits["train"]) 
churn_pred_df = pd.read_csv("hf://datasets/scikit-learn/churn-prediction/dataset.csv")
churn_pred_df.to_csv("IBM_churn_pred_Dataset.csv", index=False)
telco_churn_df.to_csv("Telco_churn_with_reason_Dataset.csv", index=False)

# EDA

In [3]:
# Describe churn_pred_df
print("Churn Prediction Dataset Description:")
print(churn_pred_df.describe(include='all'))
print("\nChurn Prediction Dataset Info:")
print(churn_pred_df.info())
print("\nChurn Prediction Dataset Null Values:")
print(churn_pred_df.isnull().sum())

Churn Prediction Dataset Description:
        customerID gender  SeniorCitizen Partner Dependents       tenure  \
count         7043   7043    7043.000000    7043       7043  7043.000000
unique        7043      2            NaN       2          2          NaN
top     7590-VHVEG   Male            NaN      No         No          NaN
freq             1   3555            NaN    3641       4933          NaN
mean           NaN    NaN       0.162147     NaN        NaN    32.371149
std            NaN    NaN       0.368612     NaN        NaN    24.559481
min            NaN    NaN       0.000000     NaN        NaN     0.000000
25%            NaN    NaN       0.000000     NaN        NaN     9.000000
50%            NaN    NaN       0.000000     NaN        NaN    29.000000
75%            NaN    NaN       0.000000     NaN        NaN    55.000000
max            NaN    NaN       1.000000     NaN        NaN    72.000000

       PhoneService MultipleLines InternetService OnlineSecurity  ...  \
count          7043          7043            7043           7043  ...
unique            2             3               3              3  ...
top             Yes            No     Fiber optic             No  ...
freq           6361          3390            3096           3498  ...
mean            NaN           NaN             NaN            NaN  ...
std             NaN           NaN             NaN            NaN  ...
min             NaN           NaN             NaN            NaN  ...
25%             NaN           NaN             NaN            NaN  ...
50%             NaN           NaN             NaN            NaN  ...
75%             NaN           NaN             NaN            NaN  ...
max             NaN           NaN             NaN            NaN  ...

       DeviceProtection TechSupport StreamingTV StreamingMovies  \
count              7043        7043        7043            7043
unique                3           3           3               3
top                  No          No          No              No
freq               3095        3473        2810            2785
mean                NaN         NaN         NaN             NaN
std                 NaN         NaN         NaN             NaN
min                 NaN         NaN         NaN             NaN
25%                 NaN         NaN         NaN             NaN
50%                 NaN         NaN         NaN             NaN
75%                 NaN         NaN         NaN             NaN
max                 NaN         NaN         NaN             NaN

              Contract PaperlessBilling     PaymentMethod MonthlyCharges  \
count             7043             7043              7043    7043.000000
unique               3                2                 4            NaN
top     Month-to-month              Yes  Electronic check            NaN
freq              3875             4171              2365            NaN
mean               NaN              NaN               NaN      64.761692
std                NaN              NaN               NaN      30.090047
min                NaN              NaN               NaN      18.250000
25%                NaN              NaN               NaN      35.500000
50%                NaN              NaN               NaN      70.350000
75%                NaN              NaN               NaN      89.850000
max                NaN              NaN               NaN     118.750000

        TotalCharges Churn
count           7043  7043
unique          6531     2
top                     No
freq              11  5174
mean             NaN   NaN
std              NaN   NaN
min              NaN   NaN
25%              NaN   NaN
50%              NaN   NaN
75%              NaN   NaN
max              NaN   NaN

[11 rows x 21 columns]

Churn Prediction Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB
None

Churn Prediction Dataset Null Values:
customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [4]:
# Describe telco_churn_df
print("\nTelco Customer Churn Dataset Description:")
print(telco_churn_df.describe(include='all'))
print("\nTelco Customer Churn Dataset Info:")
print(telco_churn_df.info())
print("\nTelco Customer Churn Dataset Null Values:")
print(telco_churn_df.isnull().sum())

Telco Customer Churn Dataset Description:
                Age  Avg Monthly GB Download  \
count   4225.000000              4225.000000
unique          NaN                      NaN
top             NaN                      NaN
freq            NaN                      NaN
mean      46.451124                20.740828
std       16.731518                20.366105
min       19.000000                 0.000000
25%       32.000000                 4.000000
50%       46.000000                17.000000
75%       60.000000                27.000000
max       80.000000                85.000000

        Avg Monthly Long Distance Charges Churn Category  \
count                         4225.000000           1121
unique                                NaN              5
top                                   NaN     Competitor
freq                                  NaN            486
mean                            22.766963            NaN
std                             15.429992            NaN
min                              0.000000            NaN
25%                              9.050000            NaN
50%                             22.570000            NaN
75%                             36.170000            NaN
max                             49.990000            NaN

                         Churn Reason  Churn Score         City         CLTV  \
count                            1121  4225.000000         4225  4225.000000
unique                             20          NaN         1085          NaN
top     Competitor had better devices          NaN  Los Angeles          NaN
freq                              188          NaN          175          NaN
mean                              NaN    58.281183          NaN  4409.751243
std                               NaN    21.197931          NaN  1170.599119
min                               NaN     5.000000          NaN  2003.000000
25%                               NaN    40.000000          NaN  3493.000000
50%                               NaN    61.000000          NaN  4531.000000
75%                               NaN    75.000000          NaN  5381.000000
max                               NaN    96.000000          NaN  6500.000000

              Contract        Country  ... Tenure in Months Total Charges  \
count             4225           4225  ...      4225.000000   4225.000000
unique               3              1  ...              NaN           NaN
top     Month-to-Month  United States  ...              NaN           NaN
freq              2193           4225  ...              NaN           NaN
mean               NaN            NaN  ...        32.681893   2306.078107
std                NaN            NaN  ...        24.621041   2271.448881
min                NaN            NaN  ...         1.000000     18.800000
25%                NaN            NaN  ...         9.000000    401.500000
50%                NaN            NaN  ...        30.000000   1424.600000
75%                NaN            NaN  ...        56.000000   3846.750000
max                NaN            NaN  ...        72.000000   8672.450000

        Total Extra Data Charges  Total Long Distance Charges Total Refunds  \
count                4225.000000                  4225.000000   4225.000000
unique                       NaN                          NaN           NaN
top                          NaN                          NaN           NaN
freq                         NaN                          NaN           NaN
mean                    6.965680                   754.719141      1.953846
std                    25.250169                   854.909725      7.814374
min                     0.000000                     0.000000      0.000000
25%                     0.000000                    67.680000      0.000000
50%                     0.000000                   396.640000      0.000000
75%                     0.000000                  1200.000000      0.000000
max                   150.000000                  3564.000000     49.790000

        Total Revenue     Under 30 Unlimited Data      Zip Code        Churn
count     4225.000000  4225.000000    4225.000000   4225.000000  4225.000000
unique            NaN          NaN            NaN           NaN          NaN
top               NaN          NaN            NaN           NaN          NaN
freq              NaN          NaN            NaN           NaN          NaN
mean      3065.809082     0.200000       0.677870  93491.892781     0.265325
std       2884.817379     0.400047       0.467348   1863.337187     0.441559
min         21.360000     0.000000       0.000000  90001.000000     0.000000
25%        592.750000     0.000000       0.000000  92102.000000     0.000000
50%       2151.470000     0.000000       1.000000  93513.000000     0.000000
75%       4845.750000     0.000000       1.000000  95337.000000     1.000000
max      11979.340000     1.000000       1.000000  96150.000000     1.000000

[11 rows x 52 columns]

Telco Customer Churn Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4225 entries, 0 to 4224
Data columns (total 52 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                4225 non-null   int64
 1   Avg Monthly GB Download            4225 non-null   int64
 2   Avg Monthly Long Distance Charges  4225 non-null   float64
 3   Churn Category                     1121 non-null   object
 4   Churn Reason                       1121 non-null   object
 5   Churn Score                        4225 non-null   int64
 6   City                               4225 non-null   object
 7   CLTV                               4225 non-null   int64
 8   Contract                           4225 non-null   object
 9   Country                            4225 non-null   object
 10  Customer ID                        4225 non-null   object
 11  Customer Status                    4225 non-null   object
 12  Dependents                         4225 non-null   int64
 13  Device Protection Plan             4225 non-null   int64
 14  Gender                             4225 non-null   object
 15  Internet Service                   4225 non-null   int64
 16  Internet Type                      3339 non-null   object
 17  Lat Long                           4225 non-null   object
 18  Latitude                           4225 non-null   float64
 19  Longitude                          4225 non-null   float64
 20  Married                            4225 non-null   int64
 21  Monthly Charge                     4225 non-null   float64
 22  Multiple Lines                     4225 non-null   int64
 23  Number of Dependents               4225 non-null   int64
 24  Number of Referrals                4225 non-null   int64
 25  Offer                              1901 non-null   object
 26  Online Backup                      4225 non-null   int64
 27  Online Security                    4225 non-null   int64
 28  Paperless Billing                  4225 non-null   int64
 29  Partner                            4225 non-null   int64
 30  Payment Method                     4225 non-null   object
 31  Phone Service                      4225 non-null   int64
 32  Population                         4225 non-null   int64
 33  Premium Tech Support               4225 non-null   int64
 34  Quarter                            4225 non-null   object
 35  Referred a Friend                  4225 non-null   int64
 36  Satisfaction Score                 4225 non-null   int64
 37  Senior Citizen                     4225 non-null   int64
 38  State                              4225 non-null   object
 39  Streaming Movies                   4225 non-null   int64
 40  Streaming Music                    4225 non-null   int64
 41  Streaming TV                       4225 non-null   int64
 42  Tenure in Months                   4225 non-null   int64
 43  Total Charges                      4225 non-null   float64
 44  Total Extra Data Charges           4225 non-null   int64
 45  Total Long Distance Charges        4225 non-null   float64
 46  Total Refunds                      4225 non-null   float64
 47  Total Revenue                      4225 non-null   float64
 48  Under 30                           4225 non-null   int64
 49  Unlimited Data                     4225 non-null   int64
 50  Zip Code                           4225 non-null   int64
 51  Churn                              4225 non-null   int64
dtypes: float64(8), int64(30), object(14)
memory usage: 1.7+ MB
None

Telco Customer Churn Dataset Null Values:
Age                                     0
Avg Monthly GB Download                 0
Avg Monthly Long Distance Charges       0
Churn Category                       3104
Churn Reason                         3104
Churn Score                             0
City                                    0
CLTV                                    0
Contract                                0
Country                                 0
Customer ID                             0
Customer Status                         0
Dependents                              0
Device Protection Plan                  0
Gender                                  0
Internet Service                        0
Internet Type                         886
Lat Long                                0
Latitude                                0
Longitude                               0
Married                                 0
Monthly Charge                          0
Multiple Lines                          0
Number of Dependents                    0
Number of Referrals                     0
Offer                                2324
Online Backup                           0
Online Security                         0
Paperless Billing                       0
Partner                                 0
Payment Method                          0
Phone Service                           0
Population                              0
Premium Tech Support                    0
Quarter                                 0
Referred a Friend                       0
Satisfaction Score                      0
Senior Citizen                          0
State                                   0
Streaming Movies                        0
Streaming Music                         0
Streaming TV                            0
Tenure in Months                        0
Total Charges                           0
Total Extra Data Charges                0
Total Long Distance Charges             0
Total Refunds                           0
Total Revenue                           0
Under 30                                0
Unlimited Data                          0
Zip Code                                0
Churn                                   0
dtype: int64

## Data Cleaning and Type conversion

In [7]:
churn_pred_df['TotalCharges'] = pd.to_numeric(churn_pred_df['TotalCharges'], errors='coerce')
churn_pred_df['TotalCharges'].fillna(churn_pred_df['TotalCharges'].median(), inplace=True)

# Address missing values explicitly
telco_churn_df['Churn Reason'].fillna('Not Provided', inplace=True)
telco_churn_df['Offer'].fillna('No Offer', inplace=True)
telco_churn_df['Internet Type'].fillna('Unknown', inplace=True)